version: '3.8'

services:
  postgresql_database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=desafio_programacao
    ports:
      - "5432:5432"
    restart: always
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=erickmazzocco@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - "5050:80"
    restart: always

volumes:
  database-data:
  pgadmin:
